//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterISS_Partner_WebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public int PartnerId { get; set; }
        public int RoleId { get; set; }
        public string UserSubMail { get; set; }
        public string NameSurname { get; set; }
        public string Password { get; set; }
        public bool IsEnabled { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
