//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterISS_Partner_WebSite.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BillView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BillView() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MasterISS_Partner_WebSite.Localization.BillView", typeof(BillView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket Bilgileri.
        /// </summary>
        public static string CompanyAddress {
            get {
                return ResourceManager.GetString("CompanyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket Bilgileri.
        /// </summary>
        public static string CorporateCustomerInfo {
            get {
                return ResourceManager.GetString("CorporateCustomerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetkili İkamet Adresi.
        /// </summary>
        public static string ExecutiveResidencyAddress {
            get {
                return ResourceManager.GetString("ExecutiveResidencyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bireysel Müşteri Bilgileri.
        /// </summary>
        public static string IndividualCustomerInfo {
            get {
                return ResourceManager.GetString("IndividualCustomerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri İkamet Adresi.
        /// </summary>
        public static string IndividualResidencyAddress {
            get {
                return ResourceManager.GetString("IndividualResidencyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diğer Telefon Numaraları.
        /// </summary>
        public static string OtherPhoneNumber {
            get {
                return ResourceManager.GetString("OtherPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Öde.
        /// </summary>
        public static string PayBill {
            get {
                return ResourceManager.GetString("PayBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Ödemede Hata var..
        /// </summary>
        public static string PayBillError {
            get {
                return ResourceManager.GetString("PayBillError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öncelikle eski faturayı ödeyiniz..
        /// </summary>
        public static string PayOldBillError {
            get {
                return ResourceManager.GetString("PayOldBillError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçiniz.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurulum Adresi.
        /// </summary>
        public static string SetupAddress {
            get {
                return ResourceManager.GetString("SetupAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abonelik Bilgileri.
        /// </summary>
        public static string SubscriptionInfo {
            get {
                return ResourceManager.GetString("SubscriptionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Krediniz.
        /// </summary>
        public static string TotalCredit {
            get {
                return ResourceManager.GetString("TotalCredit", resourceCulture);
            }
        }
    }
}
