//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterISS_Partner_WebSite.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FaultCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FaultCodes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MasterISS_Partner_WebSite.Localization.FaultCodes", typeof(FaultCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bina Kurulum Hatası.
        /// </summary>
        public static string BuildingInstallationFault {
            get {
                return ResourceManager.GetString("BuildingInstallationFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abone İptal Edildi.
        /// </summary>
        public static string ClientCancelled {
            get {
                return ResourceManager.GetString("ClientCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteriye Ulaşılamadı.
        /// </summary>
        public static string CustomerCouldNotBeReached {
            get {
                return ResourceManager.GetString("CustomerCouldNotBeReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Kurulumu Yaptı.
        /// </summary>
        public static string CustomerDidTheSetup {
            get {
                return ResourceManager.GetString("CustomerDidTheSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz adres.
        /// </summary>
        public static string InvalidAddress {
            get {
                return ResourceManager.GetString("InvalidAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modem Arızası.
        /// </summary>
        public static string ModemFault {
            get {
                return ResourceManager.GetString("ModemFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ariza Yok.
        /// </summary>
        public static string NoFault {
            get {
                return ResourceManager.GetString("NoFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randevu Alındı.
        /// </summary>
        public static string RendezvousMade {
            get {
                return ResourceManager.GetString("RendezvousMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurulum Tamamlandı.
        /// </summary>
        public static string SetupComplete {
            get {
                return ResourceManager.GetString("SetupComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telekom Genel Arızası.
        /// </summary>
        public static string TelekomGeneralFault {
            get {
                return ResourceManager.GetString("TelekomGeneralFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telekom Hat Arizası.
        /// </summary>
        public static string TelekomLineFault {
            get {
                return ResourceManager.GetString("TelekomLineFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Rezervasyon Bekleniyor..
        /// </summary>
        public static string WaitingForNewRendezvous {
            get {
                return ResourceManager.GetString("WaitingForNewRendezvous", resourceCulture);
            }
        }
    }
}
