//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterISS_Partner_WebSite.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Model {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Model() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MasterISS_Partner_WebSite.Localization.Model", typeof(Model).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetkili Adresi.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakiye.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakiye Tutarı.
        /// </summary>
        public static string BalanceAmount {
            get {
                return ResourceManager.GetString("BalanceAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BBK.
        /// </summary>
        public static string BBK {
            get {
                return ResourceManager.GetString("BBK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string BBKAddress {
            get {
                return ResourceManager.GetString("BBKAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Adresi.
        /// </summary>
        public static string BillingAddress {
            get {
                return ResourceManager.GetString("BillingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Dönemi.
        /// </summary>
        public static string BillingPeriodId {
            get {
                return ResourceManager.GetString("BillingPeriodId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğum Tarihi.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğum Yeri.
        /// </summary>
        public static string BirthPlace {
            get {
                return ResourceManager.GetString("BirthPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart Tipi.
        /// </summary>
        public static string CardType {
            get {
                return ResourceManager.GetString("CardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merkezi Sistem Numarası.
        /// </summary>
        public static string CentralSystemNo {
            get {
                return ResourceManager.GetString("CentralSystemNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket Adresi.
        /// </summary>
        public static string CompanyAddress {
            get {
                return ResourceManager.GetString("CompanyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma Ünvanı.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim Numarası.
        /// </summary>
        public static string ContactPhoneNo {
            get {
                return ResourceManager.GetString("ContactPhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Kodu.
        /// </summary>
        public static string CustomerCode {
            get {
                return ResourceManager.GetString("CustomerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC Kimlik No.
        /// </summary>
        public static string CustomerTCK {
            get {
                return ResourceManager.GetString("CustomerTCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Tipi.
        /// </summary>
        public static string CustomerTypeId {
            get {
                return ResourceManager.GetString("CustomerTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veriliş Tarihi.
        /// </summary>
        public static string DateOfIssue {
            get {
                return ResourceManager.GetString("DateOfIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bayi Kodu.
        /// </summary>
        public static string DealerCode {
            get {
                return ResourceManager.GetString("DealerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altyapı Uzaklığı.
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlçe.
        /// </summary>
        public static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        public static string Domain {
            get {
                return ResourceManager.GetString("Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitiş Tarihi.
        /// </summary>
        public static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetici Doğum Yeri.
        /// </summary>
        public static string ExecutiveBirthPlace {
            get {
                return ResourceManager.GetString("ExecutiveBirthPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetici Baba Adı.
        /// </summary>
        public static string ExecutiveFathersName {
            get {
                return ResourceManager.GetString("ExecutiveFathersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yöneticinin Anne Kızlık Soyadı.
        /// </summary>
        public static string ExecutiveMothersMaidenName {
            get {
                return ResourceManager.GetString("ExecutiveMothersMaidenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yöneticinin Anne Adı.
        /// </summary>
        public static string ExecutiveMothersName {
            get {
                return ResourceManager.GetString("ExecutiveMothersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetkili Adı.
        /// </summary>
        public static string ExecutiveName {
            get {
                return ResourceManager.GetString("ExecutiveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetici Uyruğu.
        /// </summary>
        public static string ExecutiveNationalityId {
            get {
                return ResourceManager.GetString("ExecutiveNationalityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetkili Telefon No.
        /// </summary>
        public static string ExecutivePhoneNo {
            get {
                return ResourceManager.GetString("ExecutivePhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetici Mesleği.
        /// </summary>
        public static string ExecutiveProfessionId {
            get {
                return ResourceManager.GetString("ExecutiveProfessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetici İkamet Adresi.
        /// </summary>
        public static string ExecutiveResidencyAddress {
            get {
                return ResourceManager.GetString("ExecutiveResidencyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetici Cinsiyeti.
        /// </summary>
        public static string ExecutiveSexId {
            get {
                return ResourceManager.GetString("ExecutiveSexId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetkili Soyadı.
        /// </summary>
        public static string ExecutiveSurname {
            get {
                return ResourceManager.GetString("ExecutiveSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baba Adı.
        /// </summary>
        public static string FathersName {
            get {
                return ResourceManager.GetString("FathersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adı.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kat.
        /// </summary>
        public static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altyapı Varmı?.
        /// </summary>
        public static string HasInfrastructure {
            get {
                return ResourceManager.GetString("HasInfrastructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktif Mi?.
        /// </summary>
        public static string IsEnabled {
            get {
                return ResourceManager.GetString("IsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISPCode.
        /// </summary>
        public static string ISPCode {
            get {
                return ResourceManager.GetString("ISPCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzenlenme Tarihi.
        /// </summary>
        public static string IssueDate {
            get {
                return ResourceManager.GetString("IssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyadı.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anne Kızlık Soyadı.
        /// </summary>
        public static string MothersMaidenName {
            get {
                return ResourceManager.GetString("MothersMaidenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anne Adı.
        /// </summary>
        public static string MothersName {
            get {
                return ResourceManager.GetString("MothersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uyruk.
        /// </summary>
        public static string NationalityId {
            get {
                return ResourceManager.GetString("NationalityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semt.
        /// </summary>
        public static string Neighbourhood {
            get {
                return ResourceManager.GetString("Neighbourhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diğer Telefon Numaraları.
        /// </summary>
        public static string OtherPhoneNos {
            get {
                return ResourceManager.GetString("OtherPhoneNos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa Numarası.
        /// </summary>
        public static string PageNo {
            get {
                return ResourceManager.GetString("PageNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bayi Tarifesi.
        /// </summary>
        public static string PartnerTariffID {
            get {
                return ResourceManager.GetString("PartnerTariffID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasaport Numarası.
        /// </summary>
        public static string PassportNo {
            get {
                return ResourceManager.GetString("PassportNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon Numarası.
        /// </summary>
        public static string PhoneNo {
            get {
                return ResourceManager.GetString("PhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verildiği Yer.
        /// </summary>
        public static string PlaceOfIssue {
            get {
                return ResourceManager.GetString("PlaceOfIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Durumu.
        /// </summary>
        public static string PortState {
            get {
                return ResourceManager.GetString("PortState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posta Kodu.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meslek.
        /// </summary>
        public static string ProfessionId {
            get {
                return ResourceManager.GetString("ProfessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İl.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSTN.
        /// </summary>
        public static string PSTN {
            get {
                return ResourceManager.GetString("PSTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Tarihi.
        /// </summary>
        public static string RegisterDatetime {
            get {
                return ResourceManager.GetString("RegisterDatetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İkamet Adresi.
        /// </summary>
        public static string ResidencyAddress {
            get {
                return ResourceManager.GetString("ResidencyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sıra Numarası.
        /// </summary>
        public static string RowNo {
            get {
                return ResourceManager.GetString("RowNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seri No.
        /// </summary>
        public static string SerialNo {
            get {
                return ResourceManager.GetString("SerialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurulum Adresi.
        /// </summary>
        public static string SetupAddress {
            get {
                return ResourceManager.GetString("SetupAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinsiyet.
        /// </summary>
        public static string SexId {
            get {
                return ResourceManager.GetString("SexId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hız.
        /// </summary>
        public static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abone Numarası.
        /// </summary>
        public static string SubscriberNo {
            get {
                return ResourceManager.GetString("SubscriberNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vergi Numarası.
        /// </summary>
        public static string TaxNo {
            get {
                return ResourceManager.GetString("TaxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vergi Dairesi.
        /// </summary>
        public static string TaxOffice {
            get {
                return ResourceManager.GetString("TaxOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC Kimlik Numarası.
        /// </summary>
        public static string TCKNo {
            get {
                return ResourceManager.GetString("TCKNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ünvan.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticaret Sicil Numarası.
        /// </summary>
        public static string TradeRegistrationNo {
            get {
                return ResourceManager.GetString("TradeRegistrationNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı E-Posta.
        /// </summary>
        public static string UserEmail {
            get {
                return ResourceManager.GetString("UserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı ve Soyadı.
        /// </summary>
        public static string UserNameSurname {
            get {
                return ResourceManager.GetString("UserNameSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cilt Numarası.
        /// </summary>
        public static string VolumeNo {
            get {
                return ResourceManager.GetString("VolumeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VUID.
        /// </summary>
        public static string VUID {
            get {
                return ResourceManager.GetString("VUID", resourceCulture);
            }
        }
    }
}
