//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterISS_Partner_WebSite.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class View {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal View() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MasterISS_Partner_WebSite.Localization.View", typeof(View).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı aktif etme işleminde hata oluştu. Tekrar deneyiniz..
        /// </summary>
        public static string ActiveError {
            get {
                return ResourceManager.GetString("ActiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Müşteri.
        /// </summary>
        public static string AddCustomer {
            get {
                return ResourceManager.GetString("AddCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol Ekle.
        /// </summary>
        public static string AddRole {
            get {
                return ResourceManager.GetString("AddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Ekle.
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Ekleme.
        /// </summary>
        public static string AddUserPage {
            get {
                return ResourceManager.GetString("AddUserPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş İşlemi Başarısız..
        /// </summary>
        public static string AuthenticateError {
            get {
                return ResourceManager.GetString("AuthenticateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu isimli bir rol mevcut.
        /// </summary>
        public static string AvaibleRole {
            get {
                return ResourceManager.GetString("AvaibleRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mevcut.
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Adresi.
        /// </summary>
        public static string BillingAddress {
            get {
                return ResourceManager.GetString("BillingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Listesi.
        /// </summary>
        public static string BillList {
            get {
                return ResourceManager.GetString("BillList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onayla.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oluştur.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol Oluşturma.
        /// </summary>
        public static string CreateRole {
            get {
                return ResourceManager.GetString("CreateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredi Rapor Detayları.
        /// </summary>
        public static string CreditReportDetail {
            get {
                return ResourceManager.GetString("CreditReportDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mevcut Kullanıcılar.
        /// </summary>
        public static string CurrentUsers {
            get {
                return ResourceManager.GetString("CurrentUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Sözleşme Bilgileri.
        /// </summary>
        public static string CustomerContractInfo {
            get {
                return ResourceManager.GetString("CustomerContractInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Kullanıcı Bilgileri.
        /// </summary>
        public static string CustomerCredentials {
            get {
                return ResourceManager.GetString("CustomerCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Detayları.
        /// </summary>
        public static string CustomerDetail {
            get {
                return ResourceManager.GetString("CustomerDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genel Bilgiler.
        /// </summary>
        public static string CustomerGeneralInfo {
            get {
                return ResourceManager.GetString("CustomerGeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Bilgileri.
        /// </summary>
        public static string CustomerInfo {
            get {
                return ResourceManager.GetString("CustomerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Hat Bilgileri.
        /// </summary>
        public static string CustomerLineDetails {
            get {
                return ResourceManager.GetString("CustomerLineDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Oturum Bilgileri.
        /// </summary>
        public static string CustomerSessionInfo {
            get {
                return ResourceManager.GetString("CustomerSessionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Gün .
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaylar.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sözleşmeyi İndir.
        /// </summary>
        public static string DownloadTheContract {
            get {
                return ResourceManager.GetString("DownloadTheContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem yapılırken hata oluştu..
        /// </summary>
        public static string ErrorProcessing {
            get {
                return ResourceManager.GetString("ErrorProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen &apos;.jpg&apos;,&apos;.png&apos;,&apos;.pdf&apos;,&apos;.jpeg&apos; formatında dosya gönderiniz.
        /// </summary>
        public static string FaultyFormat {
            get {
                return ResourceManager.GetString("FaultyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrele.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlk Oturum Bilgileri.
        /// </summary>
        public static string FirstSessionInfo {
            get {
                return ResourceManager.GetString("FirstSessionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşleminiz gerçekleştirilirken bir hata oluştu..
        /// </summary>
        public static string GeneralErrorDescription {
            get {
                return ResourceManager.GetString("GeneralErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir Hata Oluştu. Daha sonra tekrar deneyiniz..
        /// </summary>
        public static string Generic200ErrorCodeMessage {
            get {
                return ResourceManager.GetString("Generic200ErrorCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Sayfa.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Saat .
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kimlik Bilgileri.
        /// </summary>
        public static string IDCardInfo {
            get {
                return ResourceManager.GetString("IDCardInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Oturum Bilgileri.
        /// </summary>
        public static string LastSessionInfo {
            get {
                return ResourceManager.GetString("LastSessionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faturaları Listele.
        /// </summary>
        public static string ListBills {
            get {
                return ResourceManager.GetString("ListBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yükle.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu mail zaten mevcut..
        /// </summary>
        public static string MailValidError {
            get {
                return ResourceManager.GetString("MailValidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktif Yap.
        /// </summary>
        public static string MakeActive {
            get {
                return ResourceManager.GetString("MakeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasif Yap.
        /// </summary>
        public static string MakePassive {
            get {
                return ResourceManager.GetString("MakePassive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harita.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimum 30 gün raporlama yapabilirsiniz..
        /// </summary>
        public static string Max30Days {
            get {
                return ResourceManager.GetString("Max30Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Boyutu Maksimum 10 MB olmalı..
        /// </summary>
        public static string MaxFileSizeError {
            get {
                return ResourceManager.GetString("MaxFileSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Dakika .
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşleminiz yapılırken bir hata oluştu.Tekrar deneyiniz..
        /// </summary>
        public static string NewCustomerError {
            get {
                return ResourceManager.GetString("NewCustomerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hayır.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mevcut Değil.
        /// </summary>
        public static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu sayfada.
        /// </summary>
        public static string OnThisPage {
            get {
                return ResourceManager.GetString("OnThisPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı pasif etme işleminde hata oluştu. Tekrar deneyiniz..
        /// </summary>
        public static string PassiveError {
            get {
                return ResourceManager.GetString("PassiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adet kayıt bulundu..
        /// </summary>
        public static string RecordFound {
            get {
                return ResourceManager.GetString("RecordFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri.
        /// </summary>
        public static string ReturnBill {
            get {
                return ResourceManager.GetString("ReturnBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri.
        /// </summary>
        public static string ReturnUserOperations {
            get {
                return ResourceManager.GetString("ReturnUserOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol ismi boş geçilemez.
        /// </summary>
        public static string RoleNameValid {
            get {
                return ResourceManager.GetString("RoleNameValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen yetki seçiniz..
        /// </summary>
        public static string RoleValidPermission {
            get {
                return ResourceManager.GetString("RoleValidPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış Hakediş Detayları.
        /// </summary>
        public static string SaleAllowanceDetails {
            get {
                return ResourceManager.GetString("SaleAllowanceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış Hakediş Listesi.
        /// </summary>
        public static string SaleAllowanceList {
            get {
                return ResourceManager.GetString("SaleAllowanceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış Hakediş Detayları.
        /// </summary>
        public static string SaleAllowedDetails {
            get {
                return ResourceManager.GetString("SaleAllowedDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış Genel Hakediş Listesi.
        /// </summary>
        public static string SaleGenericAllowanceList {
            get {
                return ResourceManager.GetString("SaleGenericAllowanceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aranan Yer.
        /// </summary>
        public static string SearchedPlace {
            get {
                return ResourceManager.GetString("SearchedPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Saniye .
        /// </summary>
        public static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçiniz.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eklenti Tipini Seçiniz.
        /// </summary>
        public static string SelectAttachmentType {
            get {
                return ResourceManager.GetString("SelectAttachmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arıza Türünü Seçiniz.
        /// </summary>
        public static string SelectFaultType {
            get {
                return ResourceManager.GetString("SelectFaultType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Dosya Seçiniz.
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol Seçiniz.
        /// </summary>
        public static string SelectRole {
            get {
                return ResourceManager.GetString("SelectRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurulum Hakediş Listesi.
        /// </summary>
        public static string SetupAllowanceList {
            get {
                return ResourceManager.GetString("SetupAllowanceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurulum Hakediş Detayları.
        /// </summary>
        public static string SetupAllowedDetails {
            get {
                return ResourceManager.GetString("SetupAllowedDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurulum Hakediş Detayları.
        /// </summary>
        public static string SetupAllowenceDetails {
            get {
                return ResourceManager.GetString("SetupAllowenceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurulum Genel Hakediş Listesi.
        /// </summary>
        public static string SetupGenericAllowanceList {
            get {
                return ResourceManager.GetString("SetupGenericAllowanceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurulum Paneli.
        /// </summary>
        public static string SetupPanel {
            get {
                return ResourceManager.GetString("SetupPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şuan İşleminizi gerçekleştiremiyoruz. Lütfen bir daha deneyiniz.
        /// </summary>
        public static string SetupResponseErrorMessage {
            get {
                return ResourceManager.GetString("SetupResponseErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gösteriliyor..
        /// </summary>
        public static string Showing {
            get {
                return ResourceManager.GetString("Showing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Paneli.
        /// </summary>
        public static string SignInPanel {
            get {
                return ResourceManager.GetString("SignInPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sms Onayı.
        /// </summary>
        public static string SmsConfirmation {
            get {
                return ResourceManager.GetString("SmsConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlangıç Tarihi, Bitiş Tarihinden Büyük Olamaz..
        /// </summary>
        public static string StartDateBiggerThanEndDateError {
            get {
                return ResourceManager.GetString("StartDateBiggerThanEndDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlangıç Tarihini Doğru formatta giriniz.
        /// </summary>
        public static string StartDateValid {
            get {
                return ResourceManager.GetString("StartDateValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı.
        /// </summary>
        public static string Successful {
            get {
                return ResourceManager.GetString("Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme Başarılı.
        /// </summary>
        public static string SuccessfulPayment {
            get {
                return ResourceManager.GetString("SuccessfulPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ile.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konum Güncelleme.
        /// </summary>
        public static string UpdateClientLocation {
            get {
                return ResourceManager.GetString("UpdateClientLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşterinin Konumunu Güncelle.
        /// </summary>
        public static string UpdateGPS {
            get {
                return ResourceManager.GetString("UpdateGPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görev Tanımını Güncelle.
        /// </summary>
        public static string UpdateTaskStatus {
            get {
                return ResourceManager.GetString("UpdateTaskStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belge Yükle.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteriye Belge Yükle.
        /// </summary>
        public static string UploadDocument {
            get {
                return ResourceManager.GetString("UploadDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belge Yükle.
        /// </summary>
        public static string UploadDocumentPage {
            get {
                return ResourceManager.GetString("UploadDocumentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yanlış SMS Şifresi.
        /// </summary>
        public static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evet.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
