//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterISS_Partner_WebSite.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class View {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal View() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MasterISS_Partner_WebSite.Localization.View", typeof(View).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktif.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı aktif etme işleminde hata oluştu. Tekrar deneyiniz..
        /// </summary>
        public static string ActiveError {
            get {
                return ResourceManager.GetString("ActiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Müşteri.
        /// </summary>
        public static string AddCustomer {
            get {
                return ResourceManager.GetString("AddCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Bölge ekle.
        /// </summary>
        public static string AddNewArea {
            get {
                return ResourceManager.GetString("AddNewArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hizmet almak istediğiniz adres bilgileri ve Başvuru türü.
        /// </summary>
        public static string AddressInformationAndApplicationTypeForNewCustomer {
            get {
                return ResourceManager.GetString("AddressInformationAndApplicationTypeForNewCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol Ekle.
        /// </summary>
        public static string AddRole {
            get {
                return ResourceManager.GetString("AddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Ekle.
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Ekleme.
        /// </summary>
        public static string AddUserPage {
            get {
                return ResourceManager.GetString("AddUserPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Paneli.
        /// </summary>
        public static string AdminPanel {
            get {
                return ResourceManager.GetString("AdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Vergiler Dahil.
        /// </summary>
        public static string AllTaxesIncluded {
            get {
                return ResourceManager.GetString("AllTaxesIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödenecek Tutar.
        /// </summary>
        public static string AmountToBePaid {
            get {
                return ResourceManager.GetString("AmountToBePaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başvuru Bilgileri.
        /// </summary>
        public static string ApplicationInformation {
            get {
                return ResourceManager.GetString("ApplicationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcıyı aktif etmek istediğinden emin misin?.
        /// </summary>
        public static string AreYouSureYouWantToActivateTheUser {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToActivateTheUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteriyi Aramak İstediğinize Emin Misiniz?.
        /// </summary>
        public static string AreYouSureYouWantToCallTheCustomer {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToCallTheCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teyit Vermek İstediğinize Emin Misiniz?.
        /// </summary>
        public static string AreYouSureYouWantToConfirm {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalışma alanını silmek istediğinize emin misiniz?.
        /// </summary>
        public static string AreYouSureYouWantToDeleteTheWorkspace {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToDeleteTheWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcıyı pasif etmek istediğinden emin misin?.
        /// </summary>
        public static string AreYouSureYouWantToInactivateTheUser {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToInactivateTheUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görevi Ata.
        /// </summary>
        public static string AssignTheTask {
            get {
                return ResourceManager.GetString("AssignTheTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurulum Ekine Ata.
        /// </summary>
        public static string AssignToSetupTeam {
            get {
                return ResourceManager.GetString("AssignToSetupTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş İşlemi Başarısız..
        /// </summary>
        public static string AuthenticateError {
            get {
                return ResourceManager.GetString("AuthenticateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu isimli bir rol mevcut.
        /// </summary>
        public static string AvaibleRole {
            get {
                return ResourceManager.GetString("AvaibleRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mevcut.
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Sorgulama &amp; Ödeme.
        /// </summary>
        public static string BillCheckAndPayment {
            get {
                return ResourceManager.GetString("BillCheckAndPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Adresi.
        /// </summary>
        public static string BillingAddress {
            get {
                return ResourceManager.GetString("BillingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Listesi.
        /// </summary>
        public static string BillList {
            get {
                return ResourceManager.GetString("BillList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura İşlemleri.
        /// </summary>
        public static string BillSettings {
            get {
                return ResourceManager.GetString("BillSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tarafından.
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ara.
        /// </summary>
        public static string Call {
            get {
                return ResourceManager.GetString("Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Ara.
        /// </summary>
        public static string CallCustomer {
            get {
                return ResourceManager.GetString("CallCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İptal.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değiştir ve Kaydet.
        /// </summary>
        public static string ChangeAndSave {
            get {
                return ResourceManager.GetString("ChangeAndSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randevu Ekibini Değiştir.
        /// </summary>
        public static string ChangeRendezvousTeam {
            get {
                return ResourceManager.GetString("ChangeRendezvousTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurulum Ekibini Değiştir.
        /// </summary>
        public static string ChangeSetupTeam {
            get {
                return ResourceManager.GetString("ChangeSetupTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görev Değiştir Not Ekle.
        /// </summary>
        public static string ChangeTaskAddNote {
            get {
                return ResourceManager.GetString("ChangeTaskAddNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görev Durumunu Değiştir.
        /// </summary>
        public static string ChangeTaskStatus {
            get {
                return ResourceManager.GetString("ChangeTaskStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altyapı Sorgula.
        /// </summary>
        public static string CheckInfrastructure {
            get {
                return ResourceManager.GetString("CheckInfrastructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randevu Tarihi Seçiniz.
        /// </summary>
        public static string ChooseAnAppointmentDate {
            get {
                return ResourceManager.GetString("ChooseAnAppointmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abonesine ait faturaları ödemek için aşağıdaki listeden seçim yapınız..
        /// </summary>
        public static string ChooseSubscriberBillSelect {
            get {
                return ResourceManager.GetString("ChooseSubscriberBillSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to butonuna basınız..
        /// </summary>
        public static string ClickButton {
            get {
                return ResourceManager.GetString("ClickButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapat.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onayla.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim Telefonu.
        /// </summary>
        public static string ContactPhone {
            get {
                return ResourceManager.GetString("ContactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oluştur.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol Oluştur.
        /// </summary>
        public static string CreateRole {
            get {
                return ResourceManager.GetString("CreateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredi Rapor Detayları.
        /// </summary>
        public static string CreditReportDetail {
            get {
                return ResourceManager.GetString("CreditReportDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mevcut Operatör Adı.
        /// </summary>
        public static string CurrentOperatorName {
            get {
                return ResourceManager.GetString("CurrentOperatorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mevcut Kullanıcılar.
        /// </summary>
        public static string CurrentUsers {
            get {
                return ResourceManager.GetString("CurrentUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Sözleşme Bilgileri.
        /// </summary>
        public static string CustomerContractInfo {
            get {
                return ResourceManager.GetString("CustomerContractInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Kullanıcı Bilgileri.
        /// </summary>
        public static string CustomerCredentials {
            get {
                return ResourceManager.GetString("CustomerCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Detayları.
        /// </summary>
        public static string CustomerDetail {
            get {
                return ResourceManager.GetString("CustomerDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteriye ait Belgeler.
        /// </summary>
        public static string CustomerDocuments {
            get {
                return ResourceManager.GetString("CustomerDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteriye ait Formlar.
        /// </summary>
        public static string CustomerForms {
            get {
                return ResourceManager.GetString("CustomerForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genel Bilgiler.
        /// </summary>
        public static string CustomerGeneralInfo {
            get {
                return ResourceManager.GetString("CustomerGeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Bilgileri.
        /// </summary>
        public static string CustomerInfo {
            get {
                return ResourceManager.GetString("CustomerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Hat Bilgileri.
        /// </summary>
        public static string CustomerLineDetails {
            get {
                return ResourceManager.GetString("CustomerLineDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteriler.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Oturum Bilgileri.
        /// </summary>
        public static string CustomerSessionInfo {
            get {
                return ResourceManager.GetString("CustomerSessionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz Tarih Biçimi.
        /// </summary>
        public static string DateFormatIsNotCorrect {
            get {
                return ResourceManager.GetString("DateFormatIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih Aralığı.
        /// </summary>
        public static string DateRange {
            get {
                return ResourceManager.GetString("DateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Gün .
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaylar.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sözleşmeyi İndir.
        /// </summary>
        public static string DownloadTheContract {
            get {
                return ResourceManager.GetString("DownloadTheContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlangıç ve Bitiş çalışma saatlerini giriniz.
        /// </summary>
        public static string EnterStartAndEndWorkingHours {
            get {
                return ResourceManager.GetString("EnterStartAndEndWorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonunuza gelen SMS şifresini Giriniz..
        /// </summary>
        public static string EnterTheSMSPasswordSentToYourPhone {
            get {
                return ResourceManager.GetString("EnterTheSMSPasswordSentToYourPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı ve Şifrenizi Giriniz.
        /// </summary>
        public static string EnterYourUsernameAndPassword {
            get {
                return ResourceManager.GetString("EnterYourUsernameAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem yapılırken hata oluştu..
        /// </summary>
        public static string ErrorProcessing {
            get {
                return ResourceManager.GetString("ErrorProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen &apos;.jpg&apos;,&apos;.png&apos;,&apos;.pdf&apos;,&apos;.jpeg&apos; formatında dosya gönderiniz.
        /// </summary>
        public static string FaultyFormat {
            get {
                return ResourceManager.GetString("FaultyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen &apos;.jpg&apos;,&apos;.png&apos;,&apos;.jpeg&apos; formatında dosya gönderiniz.
        /// </summary>
        public static string FaultyFormatUpdateTaskStatus {
            get {
                return ResourceManager.GetString("FaultyFormatUpdateTaskStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosyaları buraya bırakın veya yüklemek için tıklayın..
        /// </summary>
        public static string FileDropOrClick {
            get {
                return ResourceManager.GetString("FileDropOrClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrele.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biten Kurulum.
        /// </summary>
        public static string FinishedSetup {
            get {
                return ResourceManager.GetString("FinishedSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlk Oturum Bilgileri.
        /// </summary>
        public static string FirstSessionInfo {
            get {
                return ResourceManager.GetString("FirstSessionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşleminiz gerçekleştirilirken bir hata oluştu..
        /// </summary>
        public static string GeneralErrorDescription {
            get {
                return ResourceManager.GetString("GeneralErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir Hata Oluştu. Daha sonra tekrar deneyiniz..
        /// </summary>
        public static string Generic200ErrorCodeMessage {
            get {
                return ResourceManager.GetString("Generic200ErrorCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genel Rapor.
        /// </summary>
        public static string GenericReport {
            get {
                return ResourceManager.GetString("GenericReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teyit Ver.
        /// </summary>
        public static string GiveConfirmation {
            get {
                return ResourceManager.GetString("GiveConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Sayfa.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Saat .
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim Bilgileri.
        /// </summary>
        public static string IDCardInfo {
            get {
                return ResourceManager.GetString("IDCardInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kimlik Bilgileriniz.
        /// </summary>
        public static string IDInfo {
            get {
                return ResourceManager.GetString("IDInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altyapı Sorgulama Sonucu.
        /// </summary>
        public static string InfrastructureQueryResult {
            get {
                return ResourceManager.GetString("InfrastructureQueryResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altyapı port ve alabileceğiniz hız durumunu sorgulayabilmek için adres bilgilerinizi dikkatli bir şekilde seçerek.
        /// </summary>
        public static string InOrderToInquirePortAndSpeed {
            get {
                return ResourceManager.GetString("InOrderToInquirePortAndSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekleyen Kurulum.
        /// </summary>
        public static string InProgressSetup {
            get {
                return ResourceManager.GetString("InProgressSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz Kimlik Bilgileri.
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Tahsilatlar.
        /// </summary>
        public static string LastPayments {
            get {
                return ResourceManager.GetString("LastPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Oturum Bilgileri.
        /// </summary>
        public static string LastSessionInfo {
            get {
                return ResourceManager.GetString("LastSessionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faturaları Listele.
        /// </summary>
        public static string ListBills {
            get {
                return ResourceManager.GetString("ListBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezervasyon Ekibini Listele.
        /// </summary>
        public static string ListRendezvousTeam {
            get {
                return ResourceManager.GetString("ListRendezvousTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurulum Ekibini Listele.
        /// </summary>
        public static string ListSetupTeam {
            get {
                return ResourceManager.GetString("ListSetupTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yükle.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yüklenen Bakiyeler.
        /// </summary>
        public static string LoadedBalances {
            get {
                return ResourceManager.GetString("LoadedBalances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış Yap.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu mail zaten mevcut..
        /// </summary>
        public static string MailValidError {
            get {
                return ResourceManager.GetString("MailValidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktif Yap.
        /// </summary>
        public static string MakeActive {
            get {
                return ResourceManager.GetString("MakeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasif Yap.
        /// </summary>
        public static string MakePassive {
            get {
                return ResourceManager.GetString("MakePassive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harita.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yüklenebilecek maksimum dosya boyutu 10 MB geçmemelidir..
        /// </summary>
        public static string Max10MB {
            get {
                return ResourceManager.GetString("Max10MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimum 30 gün raporlama yapabilirsiniz..
        /// </summary>
        public static string Max30Days {
            get {
                return ResourceManager.GetString("Max30Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Boyutu Maksimum 10 MB olmalı..
        /// </summary>
        public static string MaxFileSizeError {
            get {
                return ResourceManager.GetString("MaxFileSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metre.
        /// </summary>
        public static string Meter {
            get {
                return ResourceManager.GetString("Meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Dakika .
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netspeed Altyapı Sorgulama.
        /// </summary>
        public static string NetspeedInfrastructureQuery {
            get {
                return ResourceManager.GetString("NetspeedInfrastructureQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netspeed Bayi Sistemi.
        /// </summary>
        public static string NetspeedPartnerSystem {
            get {
                return ResourceManager.GetString("NetspeedPartnerSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Başvuru.
        /// </summary>
        public static string NewApplication {
            get {
                return ResourceManager.GetString("NewApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşleminiz yapılırken bir hata oluştu.Tekrar deneyiniz..
        /// </summary>
        public static string NewCustomerError {
            get {
                return ResourceManager.GetString("NewCustomerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Abonelik Başvurusu.
        /// </summary>
        public static string NewSubscriptionApplication {
            get {
                return ResourceManager.GetString("NewSubscriptionApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hayır.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mevcut Değil.
        /// </summary>
        public static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu göreve ait belge/fotoğraf bulunamadı..
        /// </summary>
        public static string NotFoundPhotoOfThisTask {
            get {
                return ResourceManager.GetString("NotFoundPhotoOfThisTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu görev için uygun Kurulum Ekibi bulunamadı..
        /// </summary>
        public static string NotFoundSetupTeamForThisTask {
            get {
                return ResourceManager.GetString("NotFoundSetupTeamForThisTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Seçim Yapınız..
        /// </summary>
        public static string NotFoundTaskNo {
            get {
                return ResourceManager.GetString("NotFoundTaskNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu sayfada.
        /// </summary>
        public static string OnThisPage {
            get {
                return ResourceManager.GetString("OnThisPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Menüsü.
        /// </summary>
        public static string OperationMenu {
            get {
                return ResourceManager.GetString("OperationMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödendi.
        /// </summary>
        public static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Tahsilatı.
        /// </summary>
        public static string PaidBillsAmount {
            get {
                return ResourceManager.GetString("PaidBillsAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasif.
        /// </summary>
        public static string Passive {
            get {
                return ResourceManager.GetString("Passive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı pasif etme işleminde hata oluştu. Tekrar deneyiniz..
        /// </summary>
        public static string PassiveError {
            get {
                return ResourceManager.GetString("PassiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetkiler.
        /// </summary>
        public static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adet.
        /// </summary>
        public static string Piece {
            get {
                return ResourceManager.GetString("Piece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeniden Sorgula.
        /// </summary>
        public static string QueryAgain {
            get {
                return ResourceManager.GetString("QueryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altyapı Sorgula.
        /// </summary>
        public static string QueryInfrastructure {
            get {
                return ResourceManager.GetString("QueryInfrastructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adet kayıt bulundu..
        /// </summary>
        public static string RecordFound {
            get {
                return ResourceManager.GetString("RecordFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaldır.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netspeed Tarafından Değiştirildi.
        /// </summary>
        public static string ReplacedByNetspeed {
            get {
                return ResourceManager.GetString("ReplacedByNetspeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raporlar.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen en az 1 Yetki seçiniz..
        /// </summary>
        public static string RequiredPermission {
            get {
                return ResourceManager.GetString("RequiredPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sıfırla.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetki Bölgesi:.
        /// </summary>
        public static string ResponsibleArea {
            get {
                return ResourceManager.GetString("ResponsibleArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri.
        /// </summary>
        public static string ReturnBill {
            get {
                return ResourceManager.GetString("ReturnBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri.
        /// </summary>
        public static string ReturnUserOperations {
            get {
                return ResourceManager.GetString("ReturnUserOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakedişler.
        /// </summary>
        public static string Revenues {
            get {
                return ResourceManager.GetString("Revenues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakediş Raporları.
        /// </summary>
        public static string RevenuesReports {
            get {
                return ResourceManager.GetString("RevenuesReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol Listesi.
        /// </summary>
        public static string RoleList {
            get {
                return ResourceManager.GetString("RoleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol ismi boş geçilemez.
        /// </summary>
        public static string RoleNameValid {
            get {
                return ResourceManager.GetString("RoleNameValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen yetki seçiniz..
        /// </summary>
        public static string RoleValidPermission {
            get {
                return ResourceManager.GetString("RoleValidPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haritaya Yönlendir.
        /// </summary>
        public static string RouteMap {
            get {
                return ResourceManager.GetString("RouteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış Hakediş Detayları.
        /// </summary>
        public static string SaleAllowanceDetails {
            get {
                return ResourceManager.GetString("SaleAllowanceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış Hasılat Listesi.
        /// </summary>
        public static string SaleAllowanceList {
            get {
                return ResourceManager.GetString("SaleAllowanceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış Hakediş Detayları.
        /// </summary>
        public static string SaleAllowedDetails {
            get {
                return ResourceManager.GetString("SaleAllowedDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış Genel Hakediş Listesi.
        /// </summary>
        public static string SaleGenericAllowanceList {
            get {
                return ResourceManager.GetString("SaleGenericAllowanceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet Ve Havuza Gönder.
        /// </summary>
        public static string SaveAndSendToPool {
            get {
                return ResourceManager.GetString("SaveAndSendToPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcıyı Kaydet.
        /// </summary>
        public static string SaveUser {
            get {
                return ResourceManager.GetString("SaveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aranan Yer.
        /// </summary>
        public static string SearchedPlace {
            get {
                return ResourceManager.GetString("SearchedPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Saniye .
        /// </summary>
        public static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçiniz.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eklenti Tipini Seçiniz.
        /// </summary>
        public static string SelectAttachmentType {
            get {
                return ResourceManager.GetString("SelectAttachmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arıza Türünü Seçiniz.
        /// </summary>
        public static string SelectFaultType {
            get {
                return ResourceManager.GetString("SelectFaultType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Dosya Seçiniz.
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil Seçiniz.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol Seçiniz.
        /// </summary>
        public static string SelectRole {
            get {
                return ResourceManager.GetString("SelectRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görevi Atamak İstediğiniz Randevu Ekibini Seçiniz.
        /// </summary>
        public static string SelectTheRendezvousTeamYouWantToAssignTheTask {
            get {
                return ResourceManager.GetString("SelectTheRendezvousTeamYouWantToAssignTheTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönder.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tekrar Havuza At.
        /// </summary>
        public static string SendBackToThePool {
            get {
                return ResourceManager.GetString("SendBackToThePool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başvuruyu Gönder.
        /// </summary>
        public static string SendTheApplication {
            get {
                return ResourceManager.GetString("SendTheApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 Haneli Hizmet Numarası mevcut operatörün faturasından veya online işlem merkezine giriş yaparak öğrenilebilir.
        ///.
        /// </summary>
        public static string ServiceNumber10DigitForNewCustomer {
            get {
                return ResourceManager.GetString("ServiceNumber10DigitForNewCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurulum Adresi.
        /// </summary>
        public static string SetupAddress {
            get {
                return ResourceManager.GetString("SetupAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurulum Hasılat Listesi.
        /// </summary>
        public static string SetupAllowanceList {
            get {
                return ResourceManager.GetString("SetupAllowanceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurulum Hakediş Detayları.
        /// </summary>
        public static string SetupAllowedDetails {
            get {
                return ResourceManager.GetString("SetupAllowedDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurulum Hakediş Detayları.
        /// </summary>
        public static string SetupAllowenceDetails {
            get {
                return ResourceManager.GetString("SetupAllowenceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurulum Genel Hakediş Listesi.
        /// </summary>
        public static string SetupGenericAllowanceList {
            get {
                return ResourceManager.GetString("SetupGenericAllowanceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurulum.
        /// </summary>
        public static string SetupPanel {
            get {
                return ResourceManager.GetString("SetupPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şuan İşleminizi gerçekleştiremiyoruz. Lütfen bir daha deneyiniz.
        /// </summary>
        public static string SetupResponseErrorMessage {
            get {
                return ResourceManager.GetString("SetupResponseErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurulum Ekibi.
        /// </summary>
        public static string SetupTeam {
            get {
                return ResourceManager.GetString("SetupTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gösteriliyor..
        /// </summary>
        public static string Showing {
            get {
                return ResourceManager.GetString("Showing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Paneli.
        /// </summary>
        public static string SignInPanel {
            get {
                return ResourceManager.GetString("SignInPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 kere hatalı giriş yaptınız. Lütfen tekrar deneyiniz..
        /// </summary>
        public static string SMSCode3TimesIncorrectlyError {
            get {
                return ResourceManager.GetString("SMSCode3TimesIncorrectlyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sms Onaylama.
        /// </summary>
        public static string SmsConfirmation {
            get {
                return ResourceManager.GetString("SmsConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlangıç Tarihi, Bitiş Tarihinden Büyük Olamaz..
        /// </summary>
        public static string StartDateBiggerThanEndDateError {
            get {
                return ResourceManager.GetString("StartDateBiggerThanEndDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlangıç Tarihini Doğru formatta giriniz.
        /// </summary>
        public static string StartDateValid {
            get {
                return ResourceManager.GetString("StartDateValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı.
        /// </summary>
        public static string Successful {
            get {
                return ResourceManager.GetString("Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme Başarılı.
        /// </summary>
        public static string SuccessfulPayment {
            get {
                return ResourceManager.GetString("SuccessfulPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son 10 kayıt listelenmektedir..
        /// </summary>
        public static string TheLast10RecordsAreListed {
            get {
                return ResourceManager.GetString("TheLast10RecordsAreListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ile.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödenmedi.
        /// </summary>
        public static string Unpaid {
            get {
                return ResourceManager.GetString("Unpaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konum Güncelle.
        /// </summary>
        public static string UpdateClientLocation {
            get {
                return ResourceManager.GetString("UpdateClientLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşterinin Konumunu Güncelle.
        /// </summary>
        public static string UpdateGPS {
            get {
                return ResourceManager.GetString("UpdateGPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol Yetkisi Değiştir.
        /// </summary>
        public static string UpdateRolePermissions {
            get {
                return ResourceManager.GetString("UpdateRolePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görev Tanımını Güncelle.
        /// </summary>
        public static string UpdateTaskStatus {
            get {
                return ResourceManager.GetString("UpdateTaskStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belge Yükle.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteriye Belge Yükle.
        /// </summary>
        public static string UploadDocument {
            get {
                return ResourceManager.GetString("UploadDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belge Yükle.
        /// </summary>
        public static string UploadDocumentPage {
            get {
                return ResourceManager.GetString("UploadDocumentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Göreve ait Yüklenen Fotoğraflar.
        /// </summary>
        public static string UploadedPhotosOfTheTask {
            get {
                return ResourceManager.GetString("UploadedPhotosOfTheTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcının Adı.
        /// </summary>
        public static string UserDisplayName {
            get {
                return ResourceManager.GetString("UserDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı E-Posta.
        /// </summary>
        public static string UserEMail {
            get {
                return ResourceManager.GetString("UserEMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Bilgileri.
        /// </summary>
        public static string UserInfo {
            get {
                return ResourceManager.GetString("UserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kullanıcı Kurulum yetkilisi Değil.
        /// </summary>
        public static string UserIsNotSetupManager {
            get {
                return ResourceManager.GetString("UserIsNotSetupManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcılar.
        /// </summary>
        public static string UserOperations {
            get {
                return ResourceManager.GetString("UserOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Paneli.
        /// </summary>
        public static string UserPanel {
            get {
                return ResourceManager.GetString("UserPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kullanıcı Kurulum yetkilisi ama yetki alanı eklenmemiş.
        /// </summary>
        public static string UserResponsibleAreaNotAdded {
            get {
                return ResourceManager.GetString("UserResponsibleAreaNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Ayarları.
        /// </summary>
        public static string UserSettings {
            get {
                return ResourceManager.GetString("UserSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu adres zaten mevcut..
        /// </summary>
        public static string ValidWorkArea {
            get {
                return ResourceManager.GetString("ValidWorkArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yüklenen Bakiyeleri Görüntüle.
        /// </summary>
        public static string ViewingLoadedBalances {
            get {
                return ResourceManager.GetString("ViewingLoadedBalances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yüklenen Fotoğrafları Görüntüle.
        /// </summary>
        public static string ViewUploadedPhotos {
            get {
                return ResourceManager.GetString("ViewUploadedPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoşgeldiniz!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalışma Bölgesi.
        /// </summary>
        public static string WorkArea {
            get {
                return ResourceManager.GetString("WorkArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalışma Bölgeleri.
        /// </summary>
        public static string WorkAreas {
            get {
                return ResourceManager.GetString("WorkAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalışma Saatleri.
        /// </summary>
        public static string WorkHours {
            get {
                return ResourceManager.GetString("WorkHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalışma Günleri.
        /// </summary>
        public static string WorkingDays {
            get {
                return ResourceManager.GetString("WorkingDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yanlış SMS Şifresi.
        /// </summary>
        public static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evet.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres Bilgileriniz.
        /// </summary>
        public static string YourAddressInformation {
            get {
                return ResourceManager.GetString("YourAddressInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakiyeniz.
        /// </summary>
        public static string YourBalance {
            get {
                return ResourceManager.GetString("YourBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta Adresiniz.
        /// </summary>
        public static string YourEmail {
            get {
                return ResourceManager.GetString("YourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GSM Numaranız.
        /// </summary>
        public static string YourGsmNumber {
            get {
                return ResourceManager.GetString("YourGsmNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyadınız.
        /// </summary>
        public static string YourLastName {
            get {
                return ResourceManager.GetString("YourLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adınız.
        /// </summary>
        public static string YourName {
            get {
                return ResourceManager.GetString("YourName", resourceCulture);
            }
        }
    }
}
