//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterISS_Partner_WebSite_Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaidBillList
    {
        public long Id { get; set; }
        public long BillId { get; set; }
        public decimal BillCost { get; set; }
        public int PartnerId { get; set; }
        public System.DateTime ChangeTime { get; set; }
        public long UserId { get; set; }
        public string SubscriberNo { get; set; }
        public string SubscriberName { get; set; }
    
        public virtual User User { get; set; }
    }
}
