//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterISS_Partner_WebSite_Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskList
    {
        public long TaskNo { get; set; }
        public string CustomerNo { get; set; }
        public string SubscriberNo { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string BBK { get; set; }
        public string XDSLNo { get; set; }
        public string PSTN { get; set; }
        public Nullable<bool> HasModem { get; set; }
        public string ModemName { get; set; }
        public Nullable<short> XDSLType { get; set; }
        public string CustomerPhoneNo { get; set; }
        public string ContactName { get; set; }
        public Nullable<short> CustomerType { get; set; }
        public string ReservationDate { get; set; }
        public string TaskIssueDate { get; set; }
        public string LastConnectionDate { get; set; }
        public Nullable<short> TaskType { get; set; }
        public Nullable<short> TaskStatus { get; set; }
        public string Details { get; set; }
        public Nullable<long> AssignToRendezvousStaff { get; set; }
        public Nullable<long> AssignToSetupTeam { get; set; }
    }
}
