//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterISS_Partner_WebSite_Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskFormList
    {
        public long Id { get; set; }
        public long TaskNo { get; set; }
        public string FileName { get; set; }
        public short AttachmentType { get; set; }
        public bool Status { get; set; }
    
        public virtual TaskList TaskList { get; set; }
    }
}
