//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterISS_Partner_WebSite_Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkArea
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public long ProvinceId { get; set; }
        public string ProvinceName { get; set; }
        public Nullable<long> DistrictId { get; set; }
        public string Districtname { get; set; }
        public Nullable<long> RuralId { get; set; }
        public string RuralName { get; set; }
        public Nullable<long> NeighbourhoodId { get; set; }
        public string NeighbourhoodName { get; set; }
    
        public virtual User User { get; set; }
    }
}
